version: '3.8'

services:
    db:
        image: mongo:latest
        restart: unless-stopped
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: homeGarden
        ports:
            - "27017:27017"    

    backend:   
        image: kuasar/homegarden-api:latest
        restart: unless-stopped
        ports:
            - "3000:3000"
        environment:
            JWT_SECRET: apiArchiOWeb
            SERVER_URL: http://localhost:3000    
            DATABASE_URL: mongodb://db:27017/homeGarden
        depends_on:
            - db

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ../..:/workspaces:cached
        command: sleep infinity    
        ports:
            - "8100:8100"
        environment:
            VITE_API_URL: http://localhost:3000/api/    
        depends_on:
            - backend
            - db

volumes:
    mongodb-data:
